### ISSUE TITLE
how can i do?

### ISSUE THREAD

**Issue by guozhongluo** [wearebase/gaze-detection-android-app#1]
Error:Execution failed for task ':clm:ndkBuild'.

> A problem occurred starting process 'command 'null/ndk-build''

**Comment by DraXus** [comment]
Please check that you have set up NDK properly in Android Studio. If it still not working try to set manually the NDK directory in this line: https://github.com/wearebase/gaze-detection-android-app/blob/master/clm/build.gradle#L24
