### ISSUE TITLE
build.gradle for clm module

### ISSUE THREAD

**Issue by seemanagar** [wearebase/gaze-detection-android-app#2]
Hi,
Is build.gradle written for linux OS ?

What changes do I have to do If I want to run it on Windows machine ?

I have already spent lot of time in trying to make it windows compatible, but have not succeeded. 
I changed the ndk-build to ndk-build.cmd but even then it is not compiling.

Any help greatly appreciated.

**Comment by DraXus** [comment]
Hi!

I've only tried to compile it in Linux. It should be possible to do it in Windows straight away assuming that you are using Android Studio. What's the error you are getting?

**Comment by DraXus** [comment]
Have you also changed the path in https://github.com/wearebase/gaze-detection-android-app/blob/master/clm/build.gradle#L24 ?

**Comment by seemanagar** [comment]
Yes I am using android studio. I have changed the path in the file you have mentioned. I am getting following error:
Execution failed for task ':clm:ndkBuild'.

> Process 'command 'C:\work\android-ndk-r10d\ndk-build.cmd'' finished with non-zero exit value 2
> I searched on google about this error, it seems this error comes when ndk-build does not find any file.
> Thats why I was wondering whether there could be some issue  which is arising because of the way paths have been set.

Thanks for such a quick response.

**Comment by DraXus** [comment]
That seems to be a problem with the NDK configuration. Have you used NDK before for other projects?

**Comment by seemanagar** [comment]
Yes, I have used NDK earlier in other projects. It works well.

**Comment by seemanagar** [comment]
But I had used NDK with eclipse not with android studio.

**Comment by DraXus** [comment]
Are you using these versions?
- Android SDK 23
- Android NDK 10e

Alternatively try to compile it in a Linux machine so we can know if it's a problem with the project configuration or maybe that there some library that depends on Linux.

**Comment by seemanagar** [comment]
Yes I am using android SDK 23.  For NDK I have android-ndk-r10d.

**Comment by seemanagar** [comment]
I am getting following errors:
src/main/clm/jni/CLM/Android.mk:12: src/main/clm/jni/CLM/../../../../../../dlib/src/main/dlib/jni/opencv/jni/OpenCV.mk: No such file or directory

Any idea why this is happening ?

**Comment by DraXus** [comment]
That might be a problem related with folder structure in Windows. Please
check that all the paths in the configuration files are correct.

**Comment by seemanagar** [comment]
But I don't see any opency.mk file under dlib module.  Do we need android opencv separately on the machine since opencv.mk comes with android opencv (I have worked with opencv in android earlier, where I had specified the full path to opencv.mk under  opencv for android)

**Comment by DraXus** [comment]
OpenCV is already included in "openCVLibrary310" folder, so there is no need to install it separately.

**Comment by seemanagar** [comment]
Thanks a lot for following it up. 

I understand your point but I did not find  opencv.mk file anywhere in the project.

**Comment by DraXus** [comment]
It should be located in "./dlib/src/main/dlib/jni/opencv/jni/OpenCV.mk". If you don't have, please make sure that you cloned the repository like this:

```
$ git clone https://github.com/wearebase/gaze-detection-android-app
$ git submodule update --init --recursive
```

**Comment by seemanagar** [comment]
Earlier I had downloaded zip directly from github.

After your reply I tried with the two commands you have pasted. I am getting following error:

Cloning into 'C:/Users/IBM_ADMIN/AndroidStudioProjects/gaze-detection-android-ap
p/dlib/src/main/dlib/jni/dlib'...
remote: Repository not found.
fatal: repository 'https://github.com/tzutalin/dlib.git/' not found
fatal: clone of 'https://github.com/tzutalin/dlib.git' into submodule path 'C:/U
sers/IBM_ADMIN/AndroidStudioProjects/gaze-detection-android-app/dlib/src/main/dl
ib/jni/dlib' failed
Failed to recurse into submodule path 'dlib/src/main/dlib'

Would you please look into it ?

**Comment by DraXus** [comment]
That's weird. Could you try the following?

```
$ cd ./dlib/src/main/
$ git clone --recursive https://github.com/tzutalin/dlib-android/ dlib
```

**Comment by seemanagar** [comment]
Yes, this one helped. Earlier cloning somehow missing dlib/src/main. There was nothing in it but after following the above commands, the folder got populated. But still some missing files:

src/main/clm/jni/CLM/Android.mk:5: src/main/clm/jni/CLM/../../../../../../dlib/src/main/dlib/jni/dlib/Android.mk: No such file or directory
I don't see any dlib folder under ./dlib/src/main/dlib/jni
I guess I shall try on a linux box, it could be that on windows some path are screwed up.

**Comment by Cristeen20** [comment]
Execution failed for task ':clm:ndkBuild'
