### ISSUE TITLE
github link for dlib is broken

### ISSUE THREAD

**Issue by seemanagar** [wearebase/gaze-detection-android-app#3]
Getting following error while cloning submodules. Please update this link

Submodule 'dlib/src/main/dlib' (https://github.com/tzutalin/dlib-android) regist                                                                                               ered for path 'dlib/src/main/dlib'
Cloning into 'C:/Users/IBM_ADMIN/gaze-detection-android-app/dlib/src/main/dlib'.                                                                                               ..
Submodule path 'dlib/src/main/dlib': checked out '32840232a6c37f03f4e31e599d544b                                                                                               b114bbe9cd'
Submodule 'jni/dlib' (https://github.com/tzutalin/dlib.git) registered for path                                                                                                'dlib/src/main/dlib/jni/dlib'
Cloning into 'C:/Users/IBM_ADMIN/gaze-detection-android-app/dlib/src/main/dlib/j                                                                                               ni/dlib'...
remote: Repository not found.
fatal: repository 'https://github.com/tzutalin/dlib.git/' not found
fatal: clone of 'https://github.com/tzutalin/dlib.git' into submodule path 'C:/U                                                                                               sers/IBM_ADMIN/gaze-detection-android-app/dlib/src/main/dlib/jni/dlib' failed
Failed to recurse into submodule path 'dlib/src/main/dlib

**Comment by seemanagar** [comment]
When I browsed the code from github, I get this link for dlib-android https://github.com/tzutalin/dlib-android/tree/32840232a6c37f03f4e31e599d544bb114bbe9cd. Code structure on this link is seems to be different from here https://github.com/tzutalin/dlib-android/.

I think there are some changes in dlib-android which are not reflected in your repo.

Would you please look into it.

**Comment by seemanagar** [comment]
I think this is the culprit. If you open this https://github.com/tzutalin/dlib-android/blob/32840232a6c37f03f4e31e599d544bb114bbe9cd/.gitmodules,  content of this file is 
submodule "jni/dlib"]
	path = jni/dlib
	url = https://github.com/tzutalin/dlib.git

**Comment by seemanagar** [comment]
I tried cloning android-dlib separately, directly from tzutalin. But even after that I get this error, dlib/src/main/dlib/jni/dlib/Android.mk not found. I checked at this page https://github.com/tzutalin/dlib-android/tree/master/jni, but it seems there is not any android.mk there as well, hence my copy also does not have it. Looks like tzutalin have changed directory structure or something. I have invested significant amount of time to debug it but without any results. Please look into it whenever you get time.

**Comment by DraXus** [comment]
Hi @seemanagar.

I'm having the same problem. Unfortunately there is not much I can do since the problem is coming from an external repository. I'll try to get the sources from my computer when I'm back at the office and publish them in this repo.

**Comment by seemanagar** [comment]
Thanks for the confirmation. Please update once resolved.

**Comment by seemanagar** [comment]
Hi, sorry to bother you again but wanted to know whether you have resolved the issue ?

**Comment by DraXus** [comment]
I've updated the submodules. Please try again and let me know if it works fine now.

Please make sure that the submodules point to:
https://github.com/wearebase/dlib-android
https://github.com/wearebase/dlib.git

**Comment by seemanagar** [comment]
Thanks for the update. I got a copy again from github.

I am getting this issue now:
src/main/clm/jni/FaceAnalyser/../../../../../../dlib/src/main/dlib/jni/dlib/dlib/image_processing/../image_processing/../geometry/../matrix/../memory_manager/../binary_search_tree/binary_search_tree_kernel_2.h:6:48: fatal error: binary_search_tree_kernel_abstract.h: No such file or directory

Would you please look into it.

**Comment by seemanagar** [comment]
This is complete log of build process

Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :clm:generateDebugSources, :clm:generateDebugAndroidTestSources, :dlib:generateDebugSources, :dlib:generateDebugAndroidTestSources, :openCVLibrary310:generateDebugSources, :openCVLibrary310:generateDebugAndroidTestSources]
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:clm:preBuild UP-TO-DATE
:clm:preReleaseBuild UP-TO-DATE
:clm:compileReleaseNdk UP-TO-DATE
:clm:compileLint
:clm:copyReleaseLint UP-TO-DATE
:clm:checkReleaseManifest
:clm:preDebugAndroidTestBuild UP-TO-DATE
:clm:preDebugBuild UP-TO-DATE
:clm:preDebugUnitTestBuild UP-TO-DATE
:clm:preReleaseUnitTestBuild UP-TO-DATE
:openCVLibrary310:preBuild UP-TO-DATE
:openCVLibrary310:preReleaseBuild UP-TO-DATE
:openCVLibrary310:compileReleaseNdk UP-TO-DATE
:openCVLibrary310:compileLint
:openCVLibrary310:copyReleaseLint UP-TO-DATE
:openCVLibrary310:mergeReleaseProguardFiles UP-TO-DATE
:openCVLibrary310:packageReleaseRenderscript UP-TO-DATE
:openCVLibrary310:checkReleaseManifest
:openCVLibrary310:prepareReleaseDependencies
:openCVLibrary310:compileReleaseRenderscript UP-TO-DATE
:openCVLibrary310:generateReleaseResValues UP-TO-DATE
:openCVLibrary310:generateReleaseResources UP-TO-DATE
:openCVLibrary310:packageReleaseResources UP-TO-DATE
:openCVLibrary310:compileReleaseAidl UP-TO-DATE
:openCVLibrary310:generateReleaseBuildConfig UP-TO-DATE
:openCVLibrary310:generateReleaseAssets UP-TO-DATE
:openCVLibrary310:mergeReleaseAssets UP-TO-DATE
:openCVLibrary310:processReleaseManifest UP-TO-DATE
:openCVLibrary310:processReleaseResources UP-TO-DATE
:openCVLibrary310:generateReleaseSources UP-TO-DATE
:openCVLibrary310:compileReleaseJavaWithJavac UP-TO-DATE
:openCVLibrary310:processReleaseJavaRes UP-TO-DATE
:openCVLibrary310:transformResourcesWithMergeJavaResForRelease UP-TO-DATE
:openCVLibrary310:transformClassesAndResourcesWithSyncLibJarsForRelease UP-TO-DATE
:openCVLibrary310:mergeReleaseJniLibFolders UP-TO-DATE
:openCVLibrary310:transformNative_libsWithMergeJniLibsForRelease UP-TO-DATE
:openCVLibrary310:transformNative_libsWithSyncJniLibsForRelease UP-TO-DATE
:openCVLibrary310:bundleRelease UP-TO-DATE
:clm:prepareComAndroidSupportAppcompatV72311Library UP-TO-DATE
:clm:prepareComAndroidSupportSupportV42311Library UP-TO-DATE
:clm:prepareGazeDetectionAndroidAppOpenCVLibrary310UnspecifiedLibrary UP-TO-DATE
:clm:prepareReleaseDependencies
:clm:compileReleaseAidl UP-TO-DATE
:clm:compileReleaseRenderscript UP-TO-DATE
:clm:generateReleaseBuildConfig UP-TO-DATE
:clm:generateReleaseAssets UP-TO-DATE
:clm:mergeReleaseAssets UP-TO-DATE
:clm:generateReleaseResValues UP-TO-DATE
:clm:generateReleaseResources UP-TO-DATE
:clm:mergeReleaseResources UP-TO-DATE
:clm:processReleaseManifest UP-TO-DATE
:clm:processReleaseResources UP-TO-DATE
:clm:generateReleaseSources UP-TO-DATE
:clm:ndkBuild
Android NDK: WARNING:src/main/clm/jni/CLM/../../../../../../dlib/src/main/dlib/jni/dlib/Android.mk:CLM: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING:src/main/clm/jni/FaceAnalyser/Android.mk:FaceAnalyser: LOCAL_LDLIBS is always ignored for static libraries    
Android NDK: WARNING:src/main/clm/jni/Android.mk:FeatureExtraction: LOCAL_LDFLAGS is always ignored for static libraries    
Android NDK: WARNING:src/main/clm/jni/Android.mk:FeatureExtraction: LOCAL_LDLIBS is always ignored for static libraries    
[armeabi-v7a] Compile++ arm  : FaceAnalyser <= FaceAnalyser.cpp
Information:(Unknown) In file included
src/main/clm/jni/FaceAnalyser/../../../../../../dlib/src/main/dlib/jni/dlib/dlib/image_processing/../image_processing/../geometry/../matrix/../memory_manager/../binary_search_tree/binary_search_tree_kernel_2.h:6:48: fatal error: binary_search_tree_kernel_abstract.h: No such file or directory
 #include "binary_search_tree_kernel_abstract.h"
                                                ^
compilation terminated.
make.exe: *** [build/intermediates/ndk/obj/local/armeabi-v7a/objs/FaceAnalyser/src/FaceAnalyser.o] Error 1
:clm:ndkBuild FAILED
Error:Execution failed for task ':clm:ndkBuild'.
> Process 'command 'C:\work\android-ndk-r10d\ndk-build.cmd'' finished with non-zero exit value 2
Information:BUILD FAILED
Information:Total time: 6.217 secs
Information:1 error
Information:0 warnings
Information:See complete output in console

**Comment by DraXus** [comment]
Have you checked if the file actually exists in that folder? It's in the repo at least https://github.com/wearebase/dlib/blob/e0aa3c1fa02ba918ad24cb5dd0e35d613af5f277/dlib/binary_search_tree/binary_search_tree_kernel_abstract.h

**Comment by seemanagar** [comment]
Yes, I checked and the file do exists, but somehow ndk is not finding it. May be ndk, needs to have current directory in the path or something. But I don't know how to do that.

**Comment by DraXus** [comment]
I've updated the version of gradle. Please try to get the sources again and let me know if that helps. I've also have the following in the ~/.bashrc file:
```
export ANDROID_NDK_HOME="$HOME/apps/android-ndk-r10e"
export PATH="$PATH:$HOME/apps/android-ndk-r10e"
```

**Comment by seemanagar** [comment]
I have fixed the problem by putting the path of the .h files in the android.mk file directly.
Thanks a lot for your help. I am working on windows, so .bashrc would not apply.

Bytheway I get an error in initializing opencv manager with my android 6 device. Earlier with some other application I got the same error, that time I fixed by including opencv in the application directly, not depending on the opencv manager.   For your app, should I do the same ?

**Comment by seemanagar** [comment]
What the best way to include opencv in the app only instead of using opencv manager

**Comment by DraXus** [comment]
It should work fine with the version for OpenCV Manager. I don't know exactly what's the issue and what should be done to integrate OpenCV directly inside the app.

I'll close the ticket so I consider that the initial issue has been solved. Please, do not hesitate in share your contribution if you make some progress, since the app is not being developed further from our side.
